# Generated by Django 5.1 on 2024-11-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_bio_customuser_company_customuser_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
    ]
